<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ccss</string>
	</array>
	<key>name</key>
	<string>CleverCSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*//.*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.unit</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\d(\.\d+)?)(px|%|em|pt)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.attribute</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s+([a-z\-]+)\s*:</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]+"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>url\([^\)]+\)</string>
			<key>name</key>
			<string>constant.url</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>operator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$?)([A-Z_]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\w\d\-_]+</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[\w\d\-_]+</string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.[\w\d\-_]+</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ccss</string>
	<key>uuid</key>
	<string>beae7f24-7269-4784-a1fc-1150f67abb6c</string>
</dict>
</plist>
