<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Paml</string>
	<key>fileTypes</key>
	<array>
		<string>paml</string>
	</array>
	<key>name</key>
	<string>Pamela HTML/XML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\#.*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[ ]+[^\s]+.*$</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*&lt;!DOCTYPE[^&gt;]+&gt;\s*$</string>
			<key>name</key>
			<string>meta.type, meta.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;[^;]+;</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\,\:\[\]]</string>
			<key>name</key>
			<string>punctuation.separator</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(%include)\s+([^\{\+]+)*.*$</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>name.tentity.ype</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^	*(&lt;)([\w\d\-_]+)(#[\w\d\-_]+)?((\.[\w\d\-_]+)*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.attribute</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.attribute</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(\s*([\-\d\w]+)\s*=([^\,\)]+)(,\s*([\-\d\w]+)\s*=([^\,\)]+))*\)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.paml</string>
	<key>uuid</key>
	<string>ef88ac95-c5e4-45b2-95d9-2d2ee98dfbe4</string>
</dict>
</plist>
